// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article class=\" flex flex-col sm:flex-row h-(--frame-height-phone-full) sm:h-(--frame-height-full) font-(family-name:--font-ubuntu) pt-[24px] mx-[24px] outline-[4px] md:outline-[6px]\"><section class=\"flex flex-col w-full sm:h-full sm:justify-center sm:space-y-(--intro-techstack-spacing) sm:w-1/2 font-(family-name:--font-ubuntu)\"><div class=\"flex flex-col justify-around text-center bg-white border-x-[0.5px] border-x-[#d9d9d9] rounded-sm w-[304px] h-[208px] mx-auto mt-[16px] px-4 place-self-center\"><h2 class=\"uppercase font-medium text-xl\">Adam Mwaniki</h2><h2 class=\"uppercase font-bold text-3xl\">Who<br>Am I?</h2><h2 class=\"font-normal text-sm\">Curious, Inquisitive, Adaptive, Mindful, Intentional, Focused, Creative, Calm, Collaborative.</h2></div></section><section class=\"flex flex-col w-full sm:w-1/2 h-(--abt-page-p-height) sm:h-full sm:justify-center pb-8 \"><div class=\"grid grid-cols-1 gap-y-4 sm:gap-y-6 md:gap-y-10 justify-around text-left bg-white rounded-2xl w-[348px] sm:w-5/6 sm:h-4/5 p-[22px] mx-auto\"><p>Hi there! I&#39;m Adam Mwaniki, pronounced /mwah  nay  key/</p><p>I develop software. <br>Together, we can go from &#8220;Let there be...&#8221; to &#8220;There it is!&#8221;</p><p>My expertise lies in full-stack development with Go and React, scalable cloud solutions backed by my Kubernetes Cloud Native Associate certification and data driven applications with Python and SQL. I specialise in translating complex ideas and requirements into clean, efficient and maintainable code. From initial design and architecture to deployment and ongoing maintenance and support.</p><p>I&#39;m always eager to embrace new challenges so <link class=\"underline text-blue\">let&#39;s connectlink> and discuss how I can bring your next idea to life! </p></div></section></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
